# Generated by Django 4.1.3 on 2022-11-01 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
