# Generated by Django 4.1.3 on 2022-11-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding_app', '0003_alter_image_project_alter_project_category_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='inappropriate_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='inappropriate_vote',
            field=models.IntegerField(default=0),
        ),
    ]
